[package]
edition = "2021"
name = "advent_of_code"
version = "0.1.0"

[workspace]
members = ["aoc_lib", "aoc_2021", "aoc_2022", "common"]

[dependencies]
common = { path = "common" }
aoc_2021 = { path = "aoc_2021" }
aoc_2022 = { path = "aoc_2022" }

clap = { version = "4.0.29", features = ["derive"] }
