[package]
edition = "2021"
name = "advent_of_code"
version = "0.1.0"

[workspace]
members = ["aoc_lib"]

[lib]
name = "aoc_lib"
path = "src/lib/mod.rs"

[[bin]]
name = "advent_of_code"
path = "src/main.rs"

[dependencies]
clap = { version = "4.0.29", features = ["derive"] }
derive_more = "0.99.17"
hashbrown = "0.13.1"
nd_vec = { path = "../nd-vec" }
num-traits = "0.2.15"
petgraph = "0.6.2"
rayon = "1.6.1"
