[package]
name = "aoc_2024"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc_lib = { path = "../aoc_lib" }
common = { path = "../common" }

indoc = "2.0.4"
itertools = "0.13.0"

nd_vec = "0.4.0"
once_cell = "1.18.0"
regex = "1.10.2"
