[package]
name = "aoc_2023"
version = "0.1.0"
edition = "2021"

[dependencies]
bitvec = "1.0.1"
common = { path = "../common" }
indoc = "2.0.4"
itertools = "0.12.0"
nd_vec = "0.4.0"
num-traits = "0.2.17"
once_cell = "1.18.0"
rayon = "1.8.0"
regex = "1.10.2"
