[package]
name = "aoc_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
nd_vec = { git = "https://github.com/connorslade/nd-vec.git" }
num-traits = "0.2.17"
once_cell = "1.18.0"
regex = "1.10.2"
