name: scaffold
on:
  workflow_dispatch:
  push:
    paths:
      - "scaffold/**"
      - "Cargo.toml"

env:
  CRATE: scaffold

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build -p ${{ env.CRATE }}
      - name: Test
        run: cargo test -p ${{ env.CRATE }}
