name: scaffold
on:
  workflow_dispatch:
  push:
    paths:
      - "scaffold/**"
      - "Cargo.toml"

env:
  CRATE: scaffold

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build -p ${{ env.CRATE }}
      - name: Test
        run: cargo test -p ${{ env.CRATE }}
